- Dockerfile
- config/database.yml
- deploy/Chart.yaml
- deploy/scripts/build_and_push
- deploy/scripts/deploy
- deploy/templates/deployment.yaml
- deploy/templates/ingress.yaml
- deploy/templates/secrets.yaml
- deploy/templates/service.yaml
Deployments scripts using Helm and DB connections.
This will be run on CircleCI once we've configured it.
Can be run locally for now.
> Deployment scripts

- Dockerfile
- config/application.rb
- deploy/scripts/deploy
- deploy/templates/deployment.yaml
- deploy/templates/ingress.yaml
- deploy/templates/secrets.yaml
Dynamic values for RAILS_ENV and hostname
Deploy this with:
```
ENV=production deploy/scripts/deploy
```
> Cleanup deploy

- deploy/templates/deployment.yaml
This will force a deployment each time
> Use dynamic CircleSha1

- Dockerfile
- Makefile
- deploy/templates/deployment.yaml
- docker-compose.yml
All hosted environments are run as 'production' for env parity.
development and test are for local runs only
> Set default rails env to production and overwrite for local runs

- .circleci/config.yml
- deploy/scripts/circle_deploy.sh
- deploy/templates/deployment.yaml
- deploy/templates/secrets.yaml
Our secrets are encrypted using git-crypt and stored in a private
repository.  Pull these in during deploy time and generate the Secret manifest from this.
> Secrets from private repo

- config/environments/production.rb
so paramater logging is disabled
> change production log level

- app/controllers/application_controller.rb
- app/controllers/complaint_controller.rb
- spec/requests/complaint_spec.rb
This will take the request from the submitter, transform it and forward it on to
Optics.
> Request spec and invoke CreateCase when a request comes in

- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/jobs/application_job.rb
- app/jobs/send_complaint_job.rb
- bin/delayed_job
- config/environments/production.rb
- db/migrate/20190916105458_create_delayed_jobs.rb
- db/schema.rb
- spec/jobs/send_complaint_job_spec.rb
- get everything in place to run jobs
- add a new SendComplaintJob
> Add delayed job and SendComplaintJob

- app/controllers/application_controller.rb
- app/controllers/complaint_controller.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
- spec/helpers/auth_helper.rb
- spec/requests/complaint_spec.rb
- no use of env vars out side of configuration
- custom config is accessed outside of application config
- nested vars are in the x object
reference: https://guides.rubyonrails.org/configuring.html#custom-configuration
> Refactror config to best practice (from rails doc)

- .circleci/config.yml
this fixes the ci pipeline in master
> [FIX] env var name for worker image generation

- app/lib/presenter/complaint.rb
- spec/presenter/complaint_spec.rb
- spec/requests/complaint_spec.rb
defaults to today if not given
> fix request date

- app/controllers/application_controller.rb
- app/jobs/send_complaint_job.rb
- config/initializers/delayed_job.rb
Delayed job requires config in order to use the rails logger
> Fix job logging

- deploy/templates/deployment.yaml
this is so we can set the production endpoint
> Get optics endpoint var from secrets

- Dockerfile
Reverts ministryofjustice/hmcts-complaints-formbuilder-adapter#62
> Revert "Fix uid not being used for local development"

- .rubocop.yml
- app/jobs/send_complaint_job.rb
- app/lib/presenter/complaint.rb
- app/lib/usecase/spawn_attachment.rb
- app/lib/usecase/spawn_attachments.rb
- app/models/attachment.rb
- spec/jobs/send_complaint_job_spec.rb
- spec/models/attachment_spec.rb
- spec/presenter/complaint_spec.rb
- spec/rails_helper.rb
- spec/requests/complaint_spec.rb
- spec/usecase/spawn_attachment_spec.rb
- spec/usecase/spawn_attachments_spec.rb
the optics payload now contains links to the attachments that will be hosted on the adaptor
> Attachments are passed to optics

- app/lib/presenter/complaint.rb
- spec/presenter/complaint_spec.rb
- spec/requests/complaint_spec.rb
so that a missing key is not a silent failure
> Remove default team from adaptor

- app/lib/gateway/optics.rb
- spec/gateway/optics_spec.rb
This would fail silently before, now it will show in sentry
> Raise if optics returns a non 200 responce

- deploy/templates/db_sweeper.yaml
`configmaps "hmcts-complaints-formbuilder-adapter-env-staging" not found`
> remove broken config parts

- Dockerfile
- Dockerfile.worker
- Makefile
- config/database.yml
- docker-compose.yml
- also aligns docker images between app and worker
- also some dockerfile optimisations
> use certificates for RDS connection

- .dependabot/config.yml
> Update Dependabot reviewers

- .circleci/config.yml
We only want to push the images if the tests pass successfully.
> Push images after tests have passed

- .circleci/config.yml
We want to be notified for any failures in the deployment pipeline
> Notify slack on deployments

- lib/tasks/list_failed_submission_ids.rake
We need to also the see the Job ID when listing the submission IDs
> Add Job ID to rake task

- .rubocop.yml
- app/controllers/correspondence_controller.rb
- app/jobs/application_job.rb
- app/jobs/send_complaint_job.rb
- app/jobs/send_correspondence_job.rb
- app/lib/presenter/correspondence.rb
- config/routes.rb
- db/migrate/20210428120407_add_submission_id_to_processed_submissions.rb
- db/schema.rb
- docker/worker/Dockerfile
- spec/jobs/send_correspondence_job_spec.rb
- spec/presenter/correspondence_spec.rb
- spec/requests/complaint_spec.rb
- spec/requests/correspondence_spec.rb
HMCTS new form API integration with OPTICS
Form metadata (classic Form builder): https://github.com/ucd-hmcts/money-claim-queries
> Correspondence submissions

- .circleci/config.yml
- deploy-eks/hmcts-complaints-formbuilder-adapter-chart/Chart.yaml
- deploy-eks/hmcts-complaints-formbuilder-adapter-chart/templates/db_sweeper.yaml
- deploy-eks/hmcts-complaints-formbuilder-adapter-chart/templates/deployment.yaml
- deploy-eks/hmcts-complaints-formbuilder-adapter-chart/templates/ingress.yaml
- deploy-eks/hmcts-complaints-formbuilder-adapter-chart/templates/secrets.yaml
- deploy-eks/hmcts-complaints-formbuilder-adapter-chart/templates/service.yaml
[Trello](https://trello.com/c/V7pdyyIn/2075-eks-021-migrate-hmcts-adapter-to-test-dev-and-test-production)
Change ingress file to 'green' and AWS weighting to 0.
> EKS Migration staging

- .github/workflows/codeql_analysis.yml
Adding codeql github action config
> Add CodeQL Github action

- .circleci/config.yml
Co-authored-by: Brendan Butler <brendan.butler@digital.justice.gov.uk>
> Update CicleCI to deploy to EKS live-dev and live-prod

- .circleci/config.yml
- deploy-eks/hmcts-complaints-formbuilder-adapter-chart/templates/ingress.yaml
- deploy/hmcts-complaints-formbuilder-adapter-chart/templates/ingress.yaml
- Send traffic to EKS cluster
- Stop deployments to Live
> Send traffic to eks

- .circleci/config.yml
> Reenable deployments to Live

- .circleci/config.yml
> Remove last deploy step to old cluster

- app/controllers/comment_controller.rb
- app/jobs/send_comment_job.rb
- app/lib/presenter/comment.rb
- app/lib/presenter/complaint.rb
- app/lib/presenter/submission_date.rb
- config/routes.rb
- deploy-eks/hmcts-complaints-formbuilder-adapter-chart/templates/config_map.yaml
- deploy-eks/hmcts-complaints-formbuilder-adapter-chart/templates/deployment.yaml
- docker/worker/Dockerfile
- spec/jobs/send_comment_job_spec.rb
- spec/presenter/comment_spec.rb
- spec/requests/comment_spec.rb
[Trello](https://trello.com/c/4ZoFU3Rs/2494-hmcts-feedback-comments-form-adapter-changes-m)
Creates a new `/v1/comment` endpoint for the new HMCTS form
> Add Comment endpoint for new form

- app/controllers/feedback_controller.rb
- app/jobs/send_feedback_job.rb
- app/lib/presenter/feedback.rb
- config/routes.rb
- docker/worker/Dockerfile
- spec/jobs/send_feedback_job_spec.rb
- spec/presenter/feedback_spec.rb
- spec/requests/feedback_spec.rb
[Trello](https://trello.com/c/nOEfATOa/2523-hmcts-praise-form-adapter-changes-m)
Create `/v1/feedback` endpoint for the new HMCTS feedback form
> Add Feedback endpoint and map values

- app/lib/presenter/feedback.rb
- spec/presenter/feedback_spec.rb
[Trello](https://trello.com/c/XcztuFOF/2594-hmcts-praise-form-adapter-modifications)
Following correspondence with Civica, they have requested we change the value of type from 'UF144908' to 'Praise'.
> Praise form

- app/lib/presenter/feedback.rb
- spec/presenter/feedback_spec.rb
- spec/requests/feedback_spec.rb
[Trello](https://trello.com/c/XcztuFOF/2594-hmcts-praise-form-adapter-modifications)
Amend 'Type' and add new parameters following correspondence with HMCTS.
> Praise form adapter amendments

- Gemfile.lock
> Update Rack to 2.2.3.1

- app/lib/presenter/feedback.rb
- spec/requests/feedback_spec.rb
Add the 'Case.Team' attributes which is the code of the team/location.
'Case.ServiceTeam' should always be 'COURTS'.
> Update Praise form attributes in submission payload

- deploy-eks/hmcts-complaints-formbuilder-adapter-chart/templates/ingress.yaml
We need to use kubernetes controllers v1.2
> Update ingress controller

- .circleci/config.yml
> Migrate to short lived ECR credentials
