- app/controllers/health_controller.rb
- config/routes.rb
- spec/controllers/health_controller_spec.rb
Kubernetes will use this to do rolling deployments, ensuring that the
application is running as opposed to just the pod being booted.
> Add health endpoint

- deploy/templates/deployment.yaml
This will ensure that the application is ready and not just the pod
> Expose health endpoint for Kubernetes rolling deploys

- .circleci/config.yml
- Dockerfile.worker
- deploy/scripts/circle_deploy.sh
- deploy/templates/deployment.yaml
- adds a new step to build the new 'worker' image
- prefixes tags with the type of image
- changes deploy scripts so that deploy tag is passed down
*New image is uploaded but not deployed to envs yet*
> Build job worker image

- app/lib/presenter/complaint.rb
- spec/presenter/complaint_spec.rb
- spec/requests/complaint_spec.rb
Case number now saving as reference in Optics.
Location is being passed along, but not being saved in Optics. We'll have to get more information on how to send this to the API. For now it can just stay present in the payload.
> Add reference and location to payload

- app/controllers/complaint_controller.rb
- app/jobs/send_complaint_job.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
- spec/jobs/send_complaint_job_spec.rb
- spec/requests/complaint_spec.rb
- spec/usecase/optics/create_case_spec.rb
1. extract ComplaintController logic to delayed job
2. use AsyncAdapter for delayed job in production
(until there is a dedicated worker service infra setup this is the only option "Since jobs share a single thread pool, long-running jobs will block short-lived jobs. Fine for dev/test; bad for production.")
> Switch cases to delayed job

- .circleci/config.yml
- Gemfile
- Gemfile.lock
- config/environments/production.rb
- deploy/scripts/circle_deploy.sh
- deploy/templates/deployment.yaml
This will give us 2 new pods that pull the worker image from ECR.
They should inherit the same secrets as environment variables as the application
pods.
> Deployment manifest and Circle deploy scripts for background workers

- app/jobs/send_complaint_job.rb
- app/lib/gateway/optics.rb
- app/lib/usecase/optics/generate_jwt_token.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
- spec/gateway/optics_spec.rb
- spec/jobs/send_complaint_job_spec.rb
- spec/usecase/optics/generate_jwt_token_spec.rb
- removes hardcoded URLs from the gateway
- allow env var OPTICS_ENDPOINT to overrite endpoint
- if OPTICS_ENDPOINT is not provieded default to the uat enviroment
> endpoint can be overridden with env var

- deploy/templates/deployment.yaml
So that combined output of workers and app can be tailed easly
i.e 
```bash
kubectl -n <namespace> logs -f -l appGroup=hmcts-complaints-formbuilder-adapter
```
> add appGroup label

- config/initializers/sentry.rb
- lib/sentry_job_argument_scrubber.rb
- spec/sentry_job_argument_scrubber_spec.rb
Sentry allows custom masking of arguments.
This class will ensure that the details of the jobs are not logged.
The error itself can be diagnosed by looking at the .last_error on the job itself.
> Ensure user data is not logged in stack traces in Sentry

- Dockerfile
- This was in place before but was overwritten in a merge
- This stops dev machines getting file permissions errors when mounting files
- it defaults back 1001 in production like before
> Fix uid not being used for local development

- config/initializers/delayed_job.rb
so sensitive data is not logged
what is looks like 
```
[ActiveJob] [SendComplaintJob] [e814aa7e-2d98-4b8e-a705-527f489ddd90] Performing SendComplaintJob (Job ID: e814aa7e-2d98-4b8e-a705-527f489ddd90) from Async(send_complaints) enqueued at 2019-09-25T15:59:36Z### args hidden ###
```
> disable logging all args in workers

- config/environments/production.rb
- config/initializers/delayed_job.rb
the monkey patch to stop args being logged in error messages is not loaded in the workers after a lot of trying i have disabled worker logging. (errors in the jobs should still be picked up by sentry anyway)
> Disable logging in workers

- app/jobs/send_complaint_job.rb
- app/models/processed_submission.rb
- db/migrate/20190930114832_create_processed_submissions.rb
- db/schema.rb
- spec/jobs/send_complaint_job_spec.rb
- spec/models/processed_submission_spec.rb
- spec/requests/complaint_spec.rb
Delayed::Job doesn't have this metric out of the box since jobs are not soft
deleted. We want to keep track of this metric to ensure the form is working well.
A future PR will expose this data on a /metrics endpoint which can be viewed
manually or piped into a dashboard like Grafana.
> Record a successful submission

- .rubocop.yml
- app/controllers/metrics_controller.rb
- app/views/metrics/show.text.erb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
- config/routes.rb
- deploy/templates/deployment.yaml
- spec/requests/metrics_spec.rb
This is currently used to see how many submissions have been submitted to
Optics.
The format of this output allows us to easily feed this into Grafana in the
future.
> Expose Delayed::Job metrics

- config/initializers/rack.rb
We have a complaint 35345 characters, which was rejected by Rails'
default limit.
Temporarily increase this as we figure out what this limit should be.
https://github.com/rack/rack/issues/318
> Increase key_space_limit for POST requests

- .circleci/config.yml
[Trello](https://trello.com/b/YIJbuKyu/form-builder-2020)
Replace image from docker hub with aws ecr in test.
There are already env vars on CircleCI named "AWS_ECR_ACCOUNT_URL", "AWS_ACCESS_KEY_ID" and "AWS_SECRET_ACCESS_KEY" which is regards to where the image hmcts-complaints-formbuilder-adapter will be pushed so I have to named the build image with the prefix "BUILD_IMAGE" to it.
> Replace image from docker hub with aws ecr in test

- deploy/templates/deployment.yaml
- deploy/templates/ingress.yaml
Kubernetes has been upgraded to 1.16. These changes are required for the resources to continue working.
Followed the guide here:
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/apiversion-changes-k8s-1-16.html#resources-deployed-using-helm-charts
https://trello.com/c/w8d8G6RM/696-cloud-platform-kubernetes-update
> Update kubernetes resources

- Dockerfile.worker
The worker also needs to use ruby 2.7.1 and the latest alpine image
> Update worker docker file

- deploy/hmcts-complaints-formbuilder-adapter-chart/templates/db_sweeper.yaml
- deploy/hmcts-complaints-formbuilder-adapter-chart/templates/deployment.yaml
- deploy/hmcts-complaints-formbuilder-adapter-chart/templates/secrets.yaml
This brings the adapter into line with the other apps on the platform.
Previously the adapter secrets were held as an actual kubernetes secret config file which the pipeline applied.
Now the secrets are mapped to a `secrets.yaml` file in this repo and the fb-deploy scripts will apply them during deployment.
https://trello.com/c/Gyg2uwc0/948-fix-hmcts-adapter-secrets
> Add secrets to deployments

- Gemfile
- Gemfile.lock
Downgrading sentry because the last version has a bug using delayed
job. https://github.com/getsentry/sentry-ruby/pull/1057
> Bump sentry to 3.0.4

- lib/tasks/list_failed_submission_ids.rake
This task will list all failed job submissions ids so we can
go in submitter to find those submission ids in the payload
Co-authored-by: Tomas Destefi <tomas.destefi@digital.justice.gov.uk>
Co-authored-by: Natalie Seeto <natalie.seeto@digital.justice.gov.uk>
Co-authored-by: Brendan Butler <brendan.butler@digital.justice.gov.uk>
> Add list submission ids rake task

- config/initializers/delayed_job.rb
This stems from a recent incident where the Optics system was unable to retrieve attachments related to a submission. The adapter kept retrying up to the default max_attempts which is 25.
This resulted in 25 cases being created for each submission as the way the Optics system works is to create the case first before then asking the adapter for any attachments related to it.
Here we set the max_attempts to be 5.
Ideally it would be best for Optics to check whether the case already exists based on the submission ID it has received in order to not attempt to create a brand new one each time.
https://trello.com/c/9oGKWZiQ/1130-hmcts-adaptor-queue-max-retries
> Set custom Delayed::Job max_attempts

- app/lib/presenter/correspondence.rb
The Type for a Correspondence submission should no longer be
'Correspondence' but rather and identifier that the OPTICS system uses
to identify the case type from the payload it receives.
> Update Correspondence Type

- app/lib/presenter/correspondence.rb
- deploy/hmcts-complaints-formbuilder-adapter-chart/templates/deployment.yaml
- deploy/hmcts-complaints-formbuilder-adapter-chart/templates/secrets.yaml
- spec/presenter/correspondence_spec.rb
For the staging environment the Correspondence Type should be
'Correspondence'. For the live environment it needs to be an identifier
that OPTICS understands in order to create the correct case.
Both of these values are set in the
hmcts-complaints-formbuilder-adapter-deploy repository
Co-authored-by: Tomas Destefi <tomas.destefi@digital.justice.gov.uk>
Co-authored-by: Natalie Seeto <natalie.seeto@digital.justice.gov.uk>
> Correspondence Type differs per environment

- app/lib/presenter/correspondence.rb
- spec/presenter/correspondence_spec.rb
- spec/requests/correspondence_spec.rb
HMCTS have updated their form pages to add an additional property which
is sent in the Submission payload: `ClaimNumber`.
This has two potential values: `CaseReferenceYes` and `CaseReferenceNo`.
Funcationally wise this replaces the previous logic around
`NewOrExistingClaim` property. This property will still exist in the
payload, as their form will pass it on to the adapter, however it is not
used at all. I have left that in the test payloads because it is still
received, just never mapped.
> Add ClaimNumber property to OPTICS payload replacing NewOrExistingClaim 

- docker-compose.yml
For some reason the main docker image has permission issues with the
entrypoint file.
The adapter DB uses postgres 11 so swap to using the postgres:11-alpine
image in the docker-compose. This is only used for testing.
> Use Postgres 11 image in docker compose

- app/lib/presenter/complaint.rb
- spec/presenter/complaint_spec.rb
- spec/requests/complaint_spec.rb
[Trello](https://trello.com/c/vQXc4WjR/2021-hmcts-complaints-form-two-additional-fields)
This PR adds two new fields, `Impact` and `ActionRequested` to the API as per the Trello story.
> Add two new fields to API

- app/lib/presenter/feedback.rb
- spec/requests/feedback_spec.rb
[Trello](https://trello.com/c/0l5OeCmI/2801-hmcts-complaints-adaptor-change-request)
This has come as a request from HMCTS, they are trying to troubleshoot an issue whereby the 'comments' and 'praise' forms have not been created with the correct location. Civica have suggested changing the order of the parameters.
> Change order of parameters

- app/lib/presenter/feedback.rb
- spec/requests/feedback_spec.rb
[Trello](https://trello.com/c/GSVqiLH2/2847-hmcts-adapter-remove-caseserviceteam-and-caseteam-params-and-add-assignedteamxs)
This was a request from the HMCTS team as they are not seeing the correct params in OPTICS.
Co-authored-by: Brendan Butler <brendan.butler@digital.justice.gov.uk>
Co-authored-by: Hellema Ibrahim <hellema.ibrahim@digital.justice.gov.uk>
> Remove two params from the feedback form

- app/lib/presenter/base_presenter.rb
- app/lib/presenter/comment.rb
- app/lib/presenter/complaint.rb
- app/lib/presenter/correspondence.rb
- app/lib/presenter/feedback.rb
- app/lib/presenter/submission_date.rb
Remove the submission date module and add the request_date method to the BasePresenter.
Change the initializer to take the form_builder_payload and use a memoized submission_answers method to cater for all the presenters that require it.
> Refactor Presenters to inherit from BasePresenter

- deploy-eks/hmcts-complaints-formbuilder-adapter-chart/templates/ingress.yaml
All beta Ingress API versions such as extensions/v1beta1 and networking.k8s.io/v1beta1 have been deprecated and are not available in Kubernetes v1.22 or the new nginx-ingress-controller v1.2
Change the apiVersion to networking.k8s.io/v1
Add pathType: ImplementationSpecific after path: /
For serviceName, rename -backend.serviceName to -backend.service.name
For String servicePort, rename -backend.servicePort to -backend.service.port.name
For Numeric servicePort, rename -backend.servicePort to -backend.service.port.number
> Stop using the beta version of Kubernetes ingress API

- .circleci/config.yml
- deploy-eks/hmcts-complaints-formbuilder-adapter-chart/templates/prometheus.yml
These rules were in the `fb-monitoring` and applied there with custom scripts and the need to have 2 eks tokens one for staging and another for production.
It seems more appropriate to have these rules in the application repo.
If this works, the rules will be deleted from the fb-monitoring repo.
> Add prometheus rules (moved from fb-monitoring)

- app/lib/presenter/complaint.rb
- spec/requests/complaint_spec.rb
We now have a concrete address component, where before forms had to implement their own address page with multiple input texts.
This address component is a bit different as it propagates the different parts as JSON.
This change makes it support both type of address for a while until all forms are migrated.
> Support both types of address
